#!/usr/bin/env bash

set -e

PYTHONPATH=src python -m unittest -v tests.test_introspection
PYTHONPATH=src python -m unittest -v tests.test_data_methods
PYTHONPATH=src python django_tests_manage.py test tests.test_http_django
PYTHONPATH=src python django_tests_manage.py test tests.test_schema_django
PYTHONPATH=src python django_tests_manage.py test tests.test_data_django
