# USER: alicia.sutton@example.com

query {
  bank_accounts {
    iban
    owner {
      id
      username
    }
  }
}

;

query {
  bank_account (id: 1) {
    iban
  }
}

;

# USER: nobody@example.com

query {
  bank_account (id: 1) {
    iban
    owner_id
  }
}

;

# USER: admin@example.com

query {
  bank_account (id: 1) {
    iban
    owner {
      id
      username
    }
  }
}

;

# USER: alicia.sutton@example.com
# (owner of this bank account)

query {
  bank_account (id: 1) {
    iban
    owner {
      id
      username
    }
  }
}
