# Generated by Django 4.0 on 2021-12-30 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('construction_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=64)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='django.house')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houses', to='django.person'),
        ),
        migrations.CreateModel(
            name='DailyOccupation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hours_per_day', models.IntegerField()),
                ('occupation', models.CharField(choices=[('EAT', 'EAT'), ('SLEEP', 'SLEEP'), ('WORK', 'WORK'), ('COMMUTE', 'COMMUTE'), ('_', '_')], max_length=7)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_occupations', to='django.person')),
            ],
        ),
    ]
