mutation {
  create_person (
    first_name: "Michel"
    last_name: "Thisfakenameiswaaaytoolongandshoulddefinitelyberejectedbecauseofit"
    username: "michel.dupont@example.com"
  ) {
    id
    first_name
    last_name
  }
}

;

mutation {
  create_person (
    first_name: "Michel"
    last_name: "Dupont"
  ) {
    id
    first_name
    last_name
  }
}

;

mutation {
  create_person (
    first_name: "Michel"
    last_name: "Dupont"
    username: "michel.dupont@example.com"
  ) {
    id
    first_name
    last_name
  }
}

;

query {
  person (id: 1) {
    id
    first_name
    last_name
  }
}

;

query {
  people (id: 1) {
    id
    first_name
    last_name
  }
}

;

mutation {
  update_person (id: 1, _: {id: 42}) {
    first_name
  }
}

;

mutation {
  update_person (id: 1, _: {first_name: "Jean-Michel"}) {
    first_name
  }
}

;

# USER: michel.dupont@example.com

mutation {
  update_person (id: 1, _: {first_name: "Jean-Michel"}) {
    first_name
  }
}

;

query {
  person (id: 1) {
    id
    first_name
    last_name
  }
}

;

mutation {
  delete_person (id: 1) {
    id
    first_name
    last_name
  }
}

;

# USER: michel.dupont@example.com

mutation {
  delete_person (id: 1) {
    id
    first_name
    last_name
  }
}

;

query {
  person (id: 1) {
    id
    first_name
    last_name
  }
}
