name: Integration tests

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7] # sqlite3.connection.backup only supports 3.7+
        # python-version: [3.6, 3.7, 3.8, 3.9]

    steps:

      # Checkout repository

      - uses: actions/checkout@v2

      # Setup Python

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Remove some files, to unbloat the VM

      - name: Clean
        run: |
          # time sudo rm -rf /usr/share/dotnet
          time sudo rm -rf /opt/ghc
          time sudo rm -rf "/usr/local/share/boost"
          time sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      # Prepare installation

      - name: Prepare
        run: |
          time python -m pip install --upgrade pip
          time ./setup.py egg_info

      # Use cache for dependencies (see https://medium.com/ai2-blog/python-caching-in-github-actions-e9452698e98d)

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('src/*.egg-info/requires.txt') }}

      # Setup dependencies
      - name: Dependencies
        run: |
          time pip install pylint
          time pip install `grep -v '^\[' src/*.egg-info/requires.txt`

      # Lint code

      - name: Lint
        run: |
          ./lint

      # Test code

      - name: Test
        run: |
          ./test
